-- Suspend ALL alerts
CALL NS11MM_DW_DEV.MONITORING.MANAGE_ALERTS('SUSPEND', 'ALL');

-- Suspend a single alert
CALL NS11MM_DW_DEV.MONITORING.MANAGE_ALERTS('SUSPEND', 'ALERT_DBT_RUN_FAILURES');

-- Resume them later
CALL NS11MM_DW_DEV.MONITORING.MANAGE_ALERTS('RESUME', 'ALL');