SHOW GRANTS TO USER DSUN;

SHOW SECRETS IN DATABASE USER$DSUN;

SHOW SECRETS IN ACCOUNT;

CREATE OR REPLACE SECRET USER$DSUN.PUBLIC.GITHUB_PAT_TEAM
    TYPE = PASSWORD
    USERNAME = 'jmyers911mm'
    PASSWORD = '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'
    COMMENT = 'GitHub PAT for museum-dbt repo access';