ns11mm_data_platform:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: om01578.east-us.azure
      user: jmyers@911memorial.org
      role: TRANSFORMER_ROLE
      warehouse: DBT_DEV_WH
      database: NS11MM_DW_DEV_JMYERS
      schema: MARTS
      threads: 4
    dev_shared:
      type: snowflake
      account: om01578.east-us.azure
      user: jmyers@911memorial.org
      role: DEPLOY_DEV_ROLE
      warehouse: DBT_DEV_WH
      database: NS11MM_DW_DEV
      schema: MARTS
      threads: 4
    prod:
      type: snowflake
      account: om01578.east-us.azure
      user: jmyers@911memorial.org
      role: DEPLOY_PROD_ROLE
      warehouse: DBT_PROD_WH
      database: NS11MM_DW_PROD
      schema: MARTS
      threads: 8
    dev_dsun:
      type: snowflake
      account: om01578.east-us.azure
      user: jmyers@911memorial.org
      role: TRANSFORMER_ROLE
      warehouse: DBT_DEV_WH
      database: NS11MM_DW_DEV_DSUN
      schema: MARTS
      threads: 4