-- TRANSFORMATION: t_fact_todays_retail_data
-- DESC: 

-- WRITES: 911DW:.fact_todays_retail_data (TableOutput)
-- WRITES: 911DW:.fact_todays_retail_product_data (TableOutput)


-- ===== STEP: Table input [TableInput] conn=Counterpoint =====
SELECT
	"USR_TODAYS_TKTS"."TKT_DT", 
	"USR_TODAYS_TKTS"."TKT_HOUR", 
	"USR_TODAYS_TKTS"."STR_ID", 
	"USR_TODAYS_TKTS"."DOC_ID", 
	"USR_TODAY_QTY_SOLD"."QTY_SOLD", 
	"USR_TODAYS_TKTS"."TKT_AM_PM", 
	"USR_TODAY_QTY_SOLD"."SAL_LIN_TOT", 
	"USR_TODAY_QTY_SOLD"."SAL_TOT_EST_COST"
FROM
  "911MemorialCP"."dbo"."USR_TODAYS_TKTS" (NOLOCK) "USR_TODAYS_TKTS" INNER JOIN
  "911MemorialCP"."dbo"."USR_TODAY_QTY_SOLD" (NOLOCK) "USR_TODAY_QTY_SOLD" ON "USR_TODAYS_TKTS"."DOC_ID"="USR_TODAY_QTY_SOLD"."DOC_ID"
WHERE 
  USR_TODAYS_TKTS.STR_ID in ('1','8', '9','10','11','12','13','14')
ORDER BY
  "USR_TODAYS_TKTS"."TKT_HOUR", "USR_TODAYS_TKTS"."DOC_ID"

-- ===== STEP: Table input 2 [TableInput] conn=Counterpoint =====
SELECT
USER_DAILY_SALES.STR_ID, USER_DAILY_SALES.DOC_ID, USER_DAILY_SALES.ITEM_NO, USER_DAILY_SALES.DESCR, USER_DAILY_SALES.QTY_SOLD, 
USER_DAILY_SALES.ITEM_VEND_NO, USER_DAILY_SALES.QTY_ON_HND, USER_DAILY_SALES.QTY_ON_PO, convert(varchar(12),USER_DAILY_SALES.TKT_DT,112) as key_date,
datepart(hour,USER_DAILY_SALES.TKT_TIM) as tkt_hour, USER_DAILY_SALES.LIN_SEQ_NO, USER_DAILY_SALES.QTY_AVAIL, USER_DAILY_SALES.CATEG_COD
FROM
  "911MemorialCP"."dbo"."USER_DAILY_SALES" (NOLOCK) "USER_DAILY_SALES"
WHERE
  (USER_DAILY_SALES.TKT_DT >= dbo.fnStartOfPeriod(GetDate(), 'T')) and (USER_DAILY_SALES.TKT_DT < dbo.fnEndOfPeriod(GetDate(), 'T'))
ORDER BY
  USER_DAILY_SALES.STR_ID, datepart(hour,USER_DAILY_SALES.TKT_TIM), USER_DAILY_SALES.ITEM_NO