-- Suspend ALL alerts
CALL MONITORING.MANAGE_ALERTS('SUSPEND', 'ALL');

-- Suspend a single alert
CALL MONITORING.MANAGE_ALERTS('SUSPEND', 'ALERT_DBT_RUN_FAILURES');

-- Resume them later
CALL MONITORING.MANAGE_ALERTS('RESUME', 'ALL');