-- GENERATED FILE -- do not edit by hand.
-- Source of truth: cortex_project/ATTENDANCE.sv.yaml
-- Regenerate: python3 scripts/generate_semantic_view_ddl.py
-- Run as the MARTS owner role. Equivalent to redeploying the .sv.yaml via the
-- Cortex project; use whichever path you have. Custom instructions and verified
-- queries in the YAML deploy via the Cortex project path, not this DDL.
CREATE OR REPLACE SEMANTIC VIEW MARTS.ATTENDANCE
  TABLES (
    DS AS MARTS.FCT_DAILY_SCAN PRIMARY KEY (DATE_KEY) WITH SYNONYMS = ('daily scan', 'fct_daily_scan'),
    TD AS MARTS.FCT_TICKET_DEMAND_FORECAST WITH SYNONYMS = ('ticket demand', 'fct_ticket_demand_forecast') COMMENT = 'Ticket demand aggregated for forecasting and presale analysis',
    TA AS MARTS.FCT_TICKET_AVAILABILITY WITH SYNONYMS = ('ticket availability', 'fct_ticket_availability') COMMENT = 'Real-time ticket capacity and utilization by date/window/type',
    TS AS MARTS.FCT_TODAY_SALES_HOURLY WITH SYNONYMS = ('today sales', 'fct_today_sales_hourly') COMMENT = 'Intraday retail sales by hour x facility (Today''s Sales Report). Additive sales/profit/units/transactions. Added 1.6.0.',
    DT AS MARTS.DIM_DATE PRIMARY KEY (DATE_KEY) WITH SYNONYMS = ('date', 'dim_date', 'calendar') COMMENT = 'Calendar date spine spanning 2000-2035 with commemoration day flag (no fiscal columns yet; fiscal calendar pending Data & AI Committee definition)',
    SM AS SEEDS.SEED_SCAN_MARKET_SEGMENT PRIMARY KEY (SEGMENT_KEY) WITH SYNONYMS = ('segment', 'market segment', 'seed_scan_market_segment') COMMENT = 'Market segment reference for scan/attendance classification'
  )
  RELATIONSHIPS (
    SCAN_TO_DATE AS DS (DATE_KEY) REFERENCES DT (DATE_KEY),
    SCAN_TO_SEGMENT AS DS (SEGMENT_KEY) REFERENCES SM (SEGMENT_KEY),
    TODAY_SALES_TO_DATE AS TS (DATE_KEY) REFERENCES DT (DATE_KEY)
  )
  FACTS (
    DS.PASSES_SCANNED AS PASSES_SCANNED,
    DS.TICKETS_SOLD AS TICKETS_SOLD,
    DS.PASSES_BUDGET AS PASSES_BUDGET,
    TD.TICKET_COUNT AS TICKET_COUNT,
    TD.TOTAL_QUANTITY AS TOTAL_QUANTITY,
    TD.TOTAL_REVENUE AS TOTAL_REVENUE,
    TD.AVG_PRICE AS AVG_PRICE,
    TD.AVG_PRESALE_LEAD_DAYS AS AVG_PRESALE_LEAD_DAYS,
    TD.MEDIAN_PRESALE_LEAD_DAYS AS MEDIAN_PRESALE_LEAD_DAYS,
    TD.TICKETS_USED AS TICKETS_USED,
    TD.TICKETS_UNUSED AS TICKETS_UNUSED,
    TD.UTILIZATION_RATE AS UTILIZATION_RATE,
    TD.QTY_SOLD_90PLUS_DAYS_OUT AS QTY_SOLD_90PLUS_DAYS_OUT,
    TD.QTY_SOLD_30PLUS_DAYS_OUT AS QTY_SOLD_30PLUS_DAYS_OUT,
    TD.QTY_SOLD_14PLUS_DAYS_OUT AS QTY_SOLD_14PLUS_DAYS_OUT,
    TD.QTY_SOLD_7PLUS_DAYS_OUT AS QTY_SOLD_7PLUS_DAYS_OUT,
    TD.QTY_SOLD_1PLUS_DAYS_OUT AS QTY_SOLD_1PLUS_DAYS_OUT,
    TD.QTY_SOLD_SAME_DAY AS QTY_SOLD_SAME_DAY,
    TD.PRESALE_PCT AS PRESALE_PCT,
    TA.TICKET_CAPACITY AS TICKET_CAPACITY,
    TA.TICKETS_RESERVED AS TICKETS_RESERVED,
    TA.TICKETS_AVAILABLE AS TICKETS_AVAILABLE,
    TA.UTILIZATION_PCT AS UTILIZATION_PCT COMMENT = 'Percentage of capacity reserved (0-100)',
    TS.SALES AS SALES,
    TS.PROFIT AS PROFIT,
    TS.UNITS AS UNITS,
    TS.COST AS COST,
    TS.TRANSACTIONS AS TRANSACTIONS
  )
  DIMENSIONS (
    DS.SEGMENT_KEY AS SEGMENT_KEY,
    DS.SEGMENT_NAME AS SEGMENT_NAME,
    DS.IS_COMMEMORATION_DAY AS IS_COMMEMORATION_DAY,
    DS.DATE_KEY AS DATE_KEY,
    DS.DATE_VALUE AS DATE_VALUE,
    TD.ENTRY_DOW AS ENTRY_DOW,
    TD.ENTRY_DAY_NAME AS ENTRY_DAY_NAME,
    TD.ENTRY_WEEK AS ENTRY_WEEK,
    TD.ENTRY_MONTH AS ENTRY_MONTH,
    TD.ENTRY_QUARTER AS ENTRY_QUARTER,
    TD.ENTRY_YEAR AS ENTRY_YEAR,
    TD.IS_WEEKEND AS IS_WEEKEND,
    TD.PLU AS PLU,
    TD.TICKET_TYPE_NAME AS TICKET_TYPE_NAME,
    TD.TICKET_KIND AS TICKET_KIND,
    TD.PRESALE_BUCKET AS PRESALE_BUCKET,
    TD.PURCHASE_CHANNEL AS PURCHASE_CHANNEL,
    TD.ENTRY_DATE AS ENTRY_DATE,
    TA.AVAILABILITY_KEY AS AVAILABILITY_KEY,
    TA.DAY_NAME AS DAY_NAME,
    TA.DAY_OF_WEEK_NUM AS DAY_OF_WEEK_NUM,
    TA.IS_WEEKEND AS IS_WEEKEND,
    TA.MONTH_NAME AS MONTH_NAME,
    TA.YEAR_NUMBER AS YEAR,
    TA.TICKET_TYPE AS TICKET_TYPE,
    TA.DEMAND_LEVEL AS DEMAND_LEVEL,
    TA.IS_OVERRIDE AS IS_OVERRIDE,
    TA.ENTRY_DATE AS ENTRY_DATE,
    TA.ENTRY_WINDOW_START AS ENTRY_WINDOW_START,
    TA.ENTRY_WINDOW_END AS ENTRY_WINDOW_END,
    TS.HOUR_OF_DAY AS HOUR_OF_DAY,
    TS.KEY_FACILITY AS KEY_FACILITY,
    TS.AREA_NAME AS AREA_NAME,
    TS.DATE_KEY AS DATE_KEY,
    TS.DATE_VALUE AS DATE_VALUE,
    DT.REPORT_DATE AS DATE_KEY COMMENT = 'Regular (non-time) date dimension so a flat SEMANTIC_VIEW() projection can select the date. Added 1.6.0.',
    DT.DAY_OF_WEEK AS DAY_OF_WEEK,
    DT.DAY_OF_WEEK_NAME AS DAY_OF_WEEK_NAME,
    DT.DAY_OF_MONTH AS DAY_OF_MONTH,
    DT.DAY_OF_YEAR AS DAY_OF_YEAR,
    DT.WEEK_OF_YEAR AS WEEK_OF_YEAR,
    DT.MONTH_OF_YEAR AS MONTH_OF_YEAR,
    DT.MONTH_NAME AS MONTH_NAME,
    DT.QUARTER_OF_YEAR AS QUARTER_OF_YEAR,
    DT.YEAR_NUMBER AS YEAR_NUMBER,
    DT.IS_WEEKEND AS IS_WEEKEND,
    DT.IS_WEEKDAY AS IS_WEEKDAY,
    DT.IS_COMMEMORATION_DAY AS IS_COMMEMORATION_DAY COMMENT = 'True for September 11 (anniversary). Flags structural anomalies across all metrics.',
    DT.IS_FIRST_OF_MONTH AS IS_FIRST_OF_MONTH,
    DT.IS_LAST_OF_MONTH AS IS_LAST_OF_MONTH,
    DT.DATE_KEY AS DATE_KEY,
    DT.DATE_DAY AS DATE_DAY,
    SM.SEGMENT_KEY AS SEGMENT_KEY,
    SM.SEGMENT_NAME AS SEGMENT_NAME,
    SM.MATCH_TYPE AS MATCH_TYPE,
    SM.MATCH_VALUE AS MATCH_VALUE,
    SM.NOTES AS NOTES
  )
  METRICS (
    DS.TOTAL_PASSES_SCANNED AS SUM(PASSES_SCANNED) COMMENT = 'Total passes scanned (attendance count)',
    DS.TOTAL_TICKETS_SCANNED AS SUM(TICKETS_SOLD) WITH SYNONYMS = ('tickets scanned', 'scans', 'gate scans') COMMENT = 'Scan-side ticket count from the daily gate-scan fact (by segment). Reconcile against DPR TOTAL_TICKETS_SOLD, the canonical tickets-sold measure.',
    DS.TOTAL_PASSES_BUDGET AS SUM(PASSES_BUDGET) COMMENT = 'Total forecast passes (DSR forecast). Added 1.6.0 for the Daily Scan Report forecast/variance columns.',
    TD.TOTAL_FORECAST_TICKET_REVENUE AS SUM(TOTAL_REVENUE) WITH SYNONYMS = ('forecast ticket revenue', 'expected ticket revenue') COMMENT = 'Total forecast-side ticket order revenue (demand/presale analysis). For actual admission revenue use the DPR view''s TOTAL_TICKET_REVENUE.',
    TD.TOTAL_TICKETS_QUANTITY AS SUM(TOTAL_QUANTITY) COMMENT = 'Total ticket quantity sold',
    TA.TOTAL_CAPACITY AS SUM(TICKET_CAPACITY) COMMENT = 'Total ticket capacity across all types',
    TA.TOTAL_RESERVED AS SUM(TICKETS_RESERVED) COMMENT = 'Total tickets reserved',
    TS.TOTAL_TODAY_SALES AS SUM(SALES) COMMENT = 'Total intraday sales',
    TS.TOTAL_TODAY_PROFIT AS SUM(PROFIT) COMMENT = 'Total intraday profit',
    TS.TOTAL_TODAY_UNITS AS SUM(UNITS) COMMENT = 'Total intraday units sold',
    TS.TOTAL_TODAY_TRANSACTIONS AS SUM(TRANSACTIONS) COMMENT = 'Total intraday transactions (ticket count)'
  )
  COMMENT = 'Attendance analytics model for museum operations. Covers daily scan counts by market segment, ticket demand forecasting with presale lead-time analysis, and real-time ticket capacity/utilization. Supports attendance budgeting, demand planning, and visitor flow analysis.';
