#!/usr/bin/env python3
"""Records tooling for ns11mm-data-platform: changes, incidents, ADRs, releases.

Follows the conventions already in the repo, so the Hub's readers keep working:
  ADRs       docs/adr/ADR_004_no_logic_in_power_bi.md, titled "# ADR-004: ..."
  Incidents  docs/dqi/DQI_0001_gateway_undercount.md, titled "# DQI-001: ..."
  Both carry their fields as a bold-key list under the title: "- **Status:** Accepted".
  Changes    changes/unreleased/CHG-<date>-<slug>.yaml (new in this design)

  new                       record a change in changes/unreleased/
  incident open             create the next DQI file and flag the affected models
  incident root-cause <ID>  replace the Root Cause section
  incident note <ID>        add a dated line to Follow-up
  adr new                   create the next numbered ADR (body on stdin)
  adr status <ID> <status>  change status; acceptance applies any supersession
  adr index                 regenerate the table in docs/adr/README.md
  release <version> [--title T]
                            move unreleased changes into changes/<version>/,
                            write its release.md, stamp last_release, resolve or
                            reopen incidents, sync incidents_open, add a row to
                            the CHANGELOG.md index
  check                     validate everything (run in CI)

Change files are immutable once released. A revert is a new change with
kind: reverted, reverts: [<id>], and usually reopens: [<incident>].
Incidents are resolved and reopened only through a released change.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------- where things live
# The Hub reads the same folders. If you move one, update hub assets/sources.js too.
ROOT = Path(__file__).resolve().parent.parent
CHANGES = ROOT / "changes"
UNRELEASED = CHANGES / "unreleased"
INCIDENTS = ROOT / "docs" / "dqi"
ADRS = ROOT / "docs" / "adr"
MODELS = ROOT / "models"
CHANGELOG = ROOT / "CHANGELOG.md"

KINDS = {"added", "changed", "fix", "removed", "reverted"}
REQUIRED = {"id", "kind", "summary", "models"}
LIST_FIELDS = ("models", "touches", "adr", "closes", "reopens", "reverts")
SEMVER = re.compile(r"^\d+\.\d+\.\d+$")
DQI_ID = re.compile(r"^DQI-\d{3,4}$")
ADR_ID = re.compile(r"^ADR-\d{3}$")
ADR_STATUSES = ("proposed", "accepted", "superseded", "deprecated")
DQI_STATUSES = ("open", "triaged", "investigating", "resolved", "closed")
DQI_DONE = ("resolved", "closed")
SEVERITIES = ("Critical", "High", "Normal")
ADR_SECTIONS = ("## Context", "## Decision", "## Options considered", "## Consequences", "## Revisit trigger")
CHANGELOG_MARKER = "<!-- releases: newest first, written by scripts/records.py -->"
ADR_INDEX_START = "<!-- adr index: generated by scripts/records.py, do not edit -->"
ADR_INDEX_END = "<!-- end adr index -->"
META_OPEN = re.compile(r"""\bmeta\s*=\s*\{[ \t]*\n""")
TODAY = dt.date.today().isoformat()


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def rel(p: Path) -> str:
    return str(p.relative_to(ROOT))


def long_date(iso: str = TODAY) -> str:
    d = dt.date.fromisoformat(iso)
    return f"{d:%B} {d.day}, {d.year}"


def slugify(text: str, sep: str = "-") -> str:
    slug = re.sub(r"[^a-z0-9]+", sep, text.lower()).strip(sep)
    if len(slug) > 40:
        cut = slug[:41]
        slug = cut[: cut.rfind(sep)] if sep in cut else slug[:40]
    return slug


# ---------------------------------------------------------------- model meta
def model_index() -> dict[str, Path]:
    index: dict[str, Path] = {}
    for p in MODELS.rglob("*.sql"):
        if p.stem in index:
            die(f"duplicate model name {p.stem}: {rel(index[p.stem])} and {rel(p)}")
        index[p.stem] = p
    return index


def _key(key: str, value_pattern: str) -> re.Pattern:
    return re.compile(rf"""(['"]{key}['"]\s*:\s*){value_pattern}""")


def has_meta(text: str) -> bool:
    return bool(META_OPEN.search(text))


def _insert(text: str, key: str, literal: str) -> str:
    m = META_OPEN.search(text)
    if not m:
        raise ValueError("no meta={ ... } block in config")
    nxt = text[m.end():].split("\n", 1)[0]
    indent = nxt[: len(nxt) - len(nxt.lstrip())] or "      "
    return text[: m.end()] + f"{indent}'{key}': {literal},\n" + text[m.end():]


def set_meta_str(text: str, key: str, value: str) -> str:
    pat = _key(key, r"""['"][^'"]*['"]""")
    if pat.search(text):
        return pat.sub(rf"\g<1>'{value}'", text, count=1)
    return _insert(text, key, f"'{value}'")


def get_meta_list(text: str, key: str) -> list[str]:
    m = _key(key, r"\[([^\]]*)\]").search(text)
    if not m:
        return []
    return [s.strip().strip("'\"") for s in m.group(2).split(",") if s.strip()]


def set_meta_list(text: str, key: str, items: list[str]) -> str:
    literal = "[" + ", ".join(f"'{i}'" for i in items) + "]"
    pat = _key(key, r"\[[^\]]*\]")
    if pat.search(text):
        return pat.sub(lambda m: m.group(1) + literal, text, count=1)
    return _insert(text, key, literal)


# ---------------------------------------------------------------- bold-key markdown records
FIELD = re.compile(r"^\s*[-*]\s*\*\*([^*:]+):\*\*\s*(.*?)\s*$")


def get_fields(text: str) -> dict[str, str]:
    """The '- **Key:** value' lines above the first section heading."""
    out = {}
    for line in text.split("\n"):
        if line.startswith("## "):
            break
        m = FIELD.match(line)
        if m:
            out[m.group(1).strip().lower()] = m.group(2)
    return out


def set_field(text: str, key: str, value: str | None) -> str:
    """Set, add, or (with None) remove one '- **Key:** value' line in the header block."""
    lines = text.split("\n")
    first_h2 = next((i for i, l in enumerate(lines) if l.startswith("## ")), len(lines))
    last_field = None
    for i in range(first_h2):
        m = FIELD.match(lines[i])
        if m:
            last_field = i
            if m.group(1).strip().lower() == key.lower():
                if value is None:
                    del lines[i]
                else:
                    lines[i] = f"- **{m.group(1).strip()}:** {value}"
                return "\n".join(lines)
    if value is None:
        return text
    at = (last_field + 1) if last_field is not None else 1
    lines.insert(at, f"- **{key}:** {value}")
    return "\n".join(lines)


def title_of(text: str) -> str:
    m = re.search(r"^#\s+(?:ADR|DQI)[-_ ]?\d+:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else "(no title)"


def _section(title: str) -> re.Pattern:
    return re.compile(rf"(^## {re.escape(title)}[ \t]*\n)(.*?)(?=^## |\Z)", re.M | re.S | re.I)


def set_section(text: str, title: str, content: str) -> str:
    block = "\n" + content.strip() + "\n\n"
    pat = _section(title)
    if pat.search(text):
        return pat.sub(lambda m: m.group(1) + block, text, count=1)
    return text.rstrip() + f"\n\n## {title}\n{block}"


def append_section(text: str, title: str, line: str, placeholder: str = "") -> str:
    pat = _section(title)
    m = pat.search(text)
    if not m:
        return text.rstrip() + f"\n\n## {title}\n\n{line}\n"
    existing = m.group(2).strip()
    if placeholder and existing == placeholder:
        existing = ""
    new = "\n" + (existing + "\n" if existing else "") + line + "\n\n"
    return text[: m.start(2)] + new + text[m.end(2):]


# ---------------------------------------------------------------- incidents (DQI)
def dqi_files() -> dict[str, Path]:
    out = {}
    if INCIDENTS.exists():
        for p in sorted(INCIDENTS.glob("DQI_*.md")):
            m = re.match(r"^DQI_(\d+)", p.name)
            if m:
                out[f"DQI-{int(m.group(1)):03d}"] = p
    return out


def norm_dqi(iid: str) -> str:
    m = re.match(r"^DQI[-_ ]?(\d+)$", iid.strip(), re.I)
    return f"DQI-{int(m.group(1)):03d}" if m else iid


def read_dqi(iid: str) -> tuple[Path, str]:
    files = dqi_files()
    iid = norm_dqi(iid)
    if iid not in files:
        die(f"no incident file for {iid} in {rel(INCIDENTS)}")
    return files[iid], files[iid].read_text()


def dqi_models(text: str) -> list[str]:
    return [m.strip(" `") for m in re.split(r"[,\s]+", get_fields(text).get("affected", "")) if m.strip(" `")]


# ---------------------------------------------------------------- ADRs
def adr_files() -> dict[str, Path]:
    out = {}
    if ADRS.exists():
        for p in sorted(ADRS.glob("ADR*.md")):
            m = re.match(r"^ADR[_-](\d{3})", p.name)
            if m:
                out[f"ADR-{m.group(1)}"] = p
    return out


def adr_status(text: str) -> str:
    raw = get_fields(text).get("status", "")
    return raw.split()[0].lower().strip(".,;:") if raw else ""


def write_adr_index() -> None:
    rows = ["| ADR | Decision | Status | Date |", "|---|---|---|---|"]
    for aid, p in adr_files().items():
        text = p.read_text()
        f = get_fields(text)
        status = f.get("status", "").split(".")[0]
        rows.append(f"| [{aid}]({p.name}) | {title_of(text)} | {status} | {f.get('date', '')} |")
    block = f"{ADR_INDEX_START}\n" + "\n".join(rows) + f"\n{ADR_INDEX_END}"
    readme = ADRS / "README.md"
    text = readme.read_text() if readme.exists() else "# Architecture decision records\n\n"
    pat = re.compile(re.escape(ADR_INDEX_START) + r".*?" + re.escape(ADR_INDEX_END), re.S)
    if pat.search(text):
        text = pat.sub(lambda m: block, text)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
        if readme.exists():
            print("note: added a generated index to docs/adr/README.md; delete the old hand table")
    ADRS.mkdir(parents=True, exist_ok=True)
    readme.write_text(text)


def apply_supersession(new_id: str, text: str) -> None:
    old = get_fields(text).get("supersedes", "").strip()
    if not old:
        return
    files = adr_files()
    if old not in files:
        die(f"{new_id} supersedes {old}, which does not exist")
    files[old].write_text(set_field(files[old].read_text(), "Status", f"Superseded by {new_id}"))
    print(f"marked {old} superseded by {new_id}")


# ---------------------------------------------------------------- change files
def load_change(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) or {}
    for f in LIST_FIELDS:
        if f in data and isinstance(data[f], str):
            data[f] = data[f].split()
    for f in ("closes", "reopens"):
        data[f] = [norm_dqi(x) for x in data.get(f, [])]
    return data


def validate(path: Path, data: dict, models: dict[str, Path]) -> list[str]:
    errs, name = [], path.name
    missing = REQUIRED - data.keys()
    if missing:
        errs.append(f"{name}: missing {sorted(missing)}")
    if data.get("id") and data["id"] != path.stem:
        errs.append(f"{name}: id does not match filename")
    if data.get("kind") and data["kind"] not in KINDS:
        errs.append(f"{name}: kind must be one of {sorted(KINDS)}")
    if data.get("kind") == "reverted" and not data.get("reverts"):
        errs.append(f"{name}: kind reverted needs reverts: [<id>]")
    if data.get("kind") == "fix" and not (data.get("closes") or data.get("why")):
        errs.append(f"{name}: a fix needs closes: [<incident>] or a why:")
    for m in data.get("models", []):
        if m not in models:
            errs.append(f"{name}: unknown model {m}")
    adrs, dqis = adr_files(), dqi_files()
    for a in data.get("adr", []):
        if a not in adrs:
            errs.append(f"{name}: no ADR file for {a}")
    for iid in data.get("closes", []) + data.get("reopens", []):
        if iid not in dqis:
            errs.append(f"{name}: no incident file for {iid}")
    return errs


# ---------------------------------------------------------------- commands
def cmd_new(args) -> None:
    if args.kind and args.summary and args.models:
        data = {"kind": args.kind, "summary": args.summary, "models": args.models}
        for f in ("touches", "adr", "closes", "reopens", "reverts"):
            if getattr(args, f):
                data[f] = getattr(args, f)
        if args.why:
            data["why"] = args.why
    else:
        def ask(label: str, required: bool = False) -> str:
            while True:
                v = input(f"{label}: ").strip()
                if v or not required:
                    return v
                print("  required")
        print("New change. Space-separate lists; leave optional fields blank.")
        data = {"kind": ask(f"kind {sorted(KINDS)}", True),
                "summary": ask("summary (one line, what changed)", True),
                "models": ask("models you touched", True).split()}
        for f in ("touches", "adr", "closes", "reopens", "reverts"):
            if v := ask(f"{f} (optional)").split():
                data[f] = v
        if v := ask("why (only if no incident explains it)"):
            data["why"] = v
    for f in ("closes", "reopens"):
        if f in data:
            data[f] = [norm_dqi(x) for x in data[f]]

    cid = f"CHG-{TODAY.replace('-', '')}-{slugify(data['summary'])}"
    data = {"id": cid, **data}
    out = UNRELEASED / f"{cid}.yaml"
    errs = validate(out, data, model_index())
    if errs:
        die("\n  ".join(["not written:"] + errs))
    if out.exists():
        die(f"{rel(out)} already exists")
    UNRELEASED.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml.safe_dump(data, sort_keys=False, width=72, allow_unicode=True))
    print(f"wrote {rel(out)}")


def cmd_incident_open(args) -> None:
    models = model_index()
    unknown = [m for m in args.affected if m not in models]
    if unknown:
        die(f"unknown model(s): {' '.join(unknown)}")
    no_meta = [rel(models[m]) for m in args.affected if not has_meta(models[m].read_text())]
    if no_meta:
        die("no meta={...} block in config, add one first:\n  " + "\n  ".join(no_meta))
    nums = [int(k[4:]) for k in dqi_files()]
    n = max(nums, default=0) + 1
    iid = f"DQI-{n:03d}"
    path = INCIDENTS / f"DQI_{n:04d}_{slugify(args.title, '_')}.md"
    detected = args.detected or TODAY
    text = "\n".join([
        f"# {iid}: {args.title.strip()}", "",
        "- **Status:** Open",
        f"- **Severity:** {args.severity}",
        f"- **Dimension:** {args.dimension}",
        f"- **Domain:** {args.domain}",
        f"- **Detected:** {detected}",
        f"- **Reported:** {TODAY}",
        f"- **Owner:** {args.owner}",
        f"- **Affected:** {', '.join(args.affected)}",
        "", "## Summary", "", args.summary.strip(),
        "", "## Detection", "", (args.detection or "Not yet recorded.").strip(),
        "", "## Impact", "", (args.impact or "Not yet assessed.").strip(),
        "", "## Root Cause", "", "Not yet known.",
        "", "## Resolution", "", "Not yet resolved.",
        "", "## Follow-up", "", f"- {TODAY} Opened by {args.owner}.", "",
    ])
    INCIDENTS.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    for m in args.affected:
        t = models[m].read_text()
        cur = get_meta_list(t, "incidents_open")
        if iid not in cur:
            models[m].write_text(set_meta_list(t, "incidents_open", cur + [iid]))
    print(f"opened {iid}: wrote {rel(path)}, flagged {len(args.affected)} model(s)")


def cmd_incident_root_cause(args) -> None:
    path, text = read_dqi(args.id)
    path.write_text(set_section(text, "Root Cause", args.text))
    print(f"updated root cause in {rel(path)}")


def cmd_incident_note(args) -> None:
    path, text = read_dqi(args.id)
    text = append_section(text, "Follow-up", f"- {TODAY} {args.text.strip()}")
    if args.status:
        if args.status.lower() in DQI_DONE:
            die("resolve an incident by releasing the change that closes it, not by hand")
        text = set_field(text, "Status", args.status.capitalize())
    path.write_text(text)
    print(f"updated {rel(path)}")


def cmd_adr_new(args) -> None:
    body = sys.stdin.read() if args.body == "-" else Path(args.body).read_text()
    missing = [h for h in ADR_SECTIONS if not re.search(rf"^{re.escape(h)}\b", body, re.M)]
    if missing:
        die("ADR body is missing sections: " + ", ".join(missing))
    if not re.search(r"^### Option .*\(set aside\)", body, re.M):
        die("an ADR needs at least one option marked (set aside); one option is a memo")
    if args.status not in ("proposed", "accepted"):
        die("a new ADR is proposed or accepted")
    files = adr_files()
    for ref in args.related + ([args.supersedes] if args.supersedes else []):
        if ref not in files:
            die(f"no ADR file for {ref}")

    n = max((int(a[4:]) for a in files), default=0) + 1
    aid = f"ADR-{n:03d}"
    path = ADRS / f"ADR_{n:03d}_{slugify(args.title, '_')}.md"
    fields = [f"- **Status:** {args.status.capitalize()}"]
    if args.category:
        fields.append(f"- **Category:** {args.category}")
    fields += [f"- **Date:** {long_date()}", f"- **Deciders:** {args.deciders}"]
    if args.consulted:
        fields.append(f"- **Consulted:** {args.consulted}")
    if args.related:
        fields.append(f"- **Related:** {', '.join(args.related)}")
    if args.applies_to:
        fields.append(f"- **Applies to:** `{args.applies_to}`")
    if args.supersedes:
        fields.append(f"- **Supersedes:** {args.supersedes}")
    text = f"# {aid}: {args.title.strip()}\n\n" + "\n".join(fields) + "\n\n" + body.strip() + "\n"
    ADRS.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"created {aid}: {rel(path)}")
    if args.status == "accepted":
        apply_supersession(aid, text)
    write_adr_index()


def cmd_adr_status(args) -> None:
    files = adr_files()
    if args.id not in files:
        die(f"no ADR file for {args.id}")
    if args.status not in ADR_STATUSES:
        die(f"status must be one of {', '.join(ADR_STATUSES)}")
    if args.status == "superseded":
        die("set the replacing ADR to accepted instead; supersession follows from it")
    text = set_field(files[args.id].read_text(), "Status", args.status.capitalize())
    files[args.id].write_text(text)
    print(f"{args.id} is now {args.status}")
    if args.status == "accepted":
        apply_supersession(args.id, text)
    write_adr_index()


def cmd_adr_index(args) -> None:
    write_adr_index()
    print("wrote docs/adr/README.md index")


KIND_HEADINGS = [("added", "Added"), ("changed", "Changed"), ("fix", "Fixed"), ("removed", "Removed"), ("reverted", "Reverted")]


def release_notes(version: str, title: str, changes: list[dict]) -> str:
    """changes/<version>/release.md: the human-readable notes, built from the release's change records."""
    L = [f"# {version}: {title}", "", f"- **Date:** {TODAY}", f"- **Version:** {version}", ""]
    for kind, heading in KIND_HEADINGS:
        group = [c for c in changes if c.get("kind") == kind]
        if not group:
            continue
        L += [f"## {heading}", ""]
        for c in group:
            extra = []
            if c.get("models"):
                extra.append("Models: " + ", ".join(f"`{m}`" for m in c["models"]))
            if c.get("closes"):
                extra.append("Resolves " + ", ".join(c["closes"]))
            if c.get("reopens"):
                extra.append("Reopens " + ", ".join(c["reopens"]))
            if c.get("reverts"):
                extra.append("Reverts " + ", ".join(f"`{r}`" for r in c["reverts"]))
            if c.get("adr"):
                extra.append("Under " + ", ".join(c["adr"]))
            L.append(f"- **{c['summary']}** (`{c['id']}`)." + (" " + ". ".join(extra) + "." if extra else ""))
            if c.get("why"):
                L.append(f"  {c['why']}")
        L.append("")
    return "\n".join(L)


def cmd_release(args) -> None:
    version, dry = args.version, args.dry_run
    if not SEMVER.match(version):
        die(f"{version} is not x.y.z")
    target = CHANGES / version
    if target.exists():
        die(f"{rel(target)} already exists")
    files = sorted(UNRELEASED.glob("*.yaml"))
    if not files:
        die("no unreleased changes")

    models = model_index()
    changes, errs = [], []
    for f in files:
        data = load_change(f)
        errs += validate(f, data, models)
        changes.append((f, data))
    if errs:
        die("fix these first:\n  " + "\n  ".join(errs))

    # Plan every write before making any, so a failure never leaves a half release.
    texts = {name: p.read_text() for name, p in models.items()}
    incidents: dict[str, tuple[Path, str]] = {}
    touched: set[str] = set()
    log: list[str] = []

    for _, d in changes:
        for m in d["models"]:
            if has_meta(texts[m]):
                texts[m] = set_meta_str(texts[m], "last_release", version)
            touched.add(m)
    for _, d in changes:
        cid = d["id"]
        for iid in d.get("closes", []):
            path, text = incidents.get(iid) or read_dqi(iid)
            text = set_field(text, "Status", "Resolved")
            text = set_field(text, "Fixed by", cid)
            text = append_section(text, "Resolution", f"Fixed in {version} by {cid}.", "Not yet resolved.")
            text = append_section(text, "Follow-up", f"- {TODAY} Resolved in {version} ({cid}).")
            incidents[iid] = (path, text)
            for m, t in texts.items():
                if iid in get_meta_list(t, "incidents_open"):
                    texts[m] = set_meta_list(t, "incidents_open", [x for x in get_meta_list(t, "incidents_open") if x != iid])
                    touched.add(m)
            log.append(f"resolve {iid} (by {cid})")
        for iid in d.get("reopens", []):
            path, text = incidents.get(iid) or read_dqi(iid)
            text = set_field(text, "Status", "Open")
            text = set_field(text, "Fixed by", None)
            text = append_section(text, "Resolution", f"Reverted in {version} by {cid}: {d['summary']}")
            text = append_section(text, "Follow-up", f"- {TODAY} Reopened in {version} ({cid}).")
            incidents[iid] = (path, text)
            for m in dqi_models(text):
                if m not in texts:
                    continue
                cur = get_meta_list(texts[m], "incidents_open")
                if iid not in cur and has_meta(texts[m]):
                    texts[m] = set_meta_list(texts[m], "incidents_open", cur + [iid])
                touched.add(m)
            log.append(f"reopen  {iid} (by {cid})")

    no_meta = sorted(rel(models[m]) for m in touched if not has_meta(texts[m]))
    if no_meta:
        die("no meta={...} block in config, add one first:\n  " + "\n  ".join(no_meta))

    print(f"Release {version}: {len(changes)} change(s), {len(touched)} model(s)")
    for m in sorted(touched):
        print(f"  {'would stamp' if dry else 'stamped':12} {rel(models[m])}")
    for line in log:
        print(f"  {('would ' if dry else '') + line}")
    if dry:
        return

    for m in touched:
        models[m].write_text(texts[m])
    for path, text in incidents.values():
        path.write_text(text)
    target.mkdir(parents=True)
    for f, _ in changes:
        f.rename(target / f.name)

    title = (args.title or "").strip() or f"Release {version}"
    (target / "release.md").write_text(release_notes(version, title, [d for _, d in changes]))
    row = f"| {version} | {TODAY} | {title} | [changes/{version}/release.md](changes/{version}/release.md) |"
    if CHANGELOG.exists() and CHANGELOG_MARKER in CHANGELOG.read_text():
        text = CHANGELOG.read_text().replace(CHANGELOG_MARKER, f"{CHANGELOG_MARKER}\n{row}", 1)
    else:
        text = ("# Changelog\n\nAll notable changes, newest first. Each release's notes live in "
                "`changes/<version>/release.md`, beside its change records.\n\n"
                "| Version | Date | Release | Notes |\n|---|---|---|---|\n"
                f"{CHANGELOG_MARKER}\n{row}\n")
    CHANGELOG.write_text(text)
    print(f"  moved changes to changes/{version}/, wrote its release.md, updated CHANGELOG.md")
    print("Review with `git diff`, then commit.")


def cmd_check(args) -> None:
    models = model_index()
    errs, seen, reverted = [], {}, set()
    for f in sorted(CHANGES.rglob("*.yaml")) if CHANGES.exists() else []:
        data = load_change(f)
        errs += validate(f, data, models)
        reverted.update(data.get("reverts", []))
        cid = data.get("id")
        if cid in seen:
            errs.append(f"duplicate id {cid}: {seen[cid]} and {rel(f)}")
        seen[cid] = rel(f)

    open_on_models: dict[str, list[str]] = {}
    for name, p in models.items():
        for iid in get_meta_list(p.read_text(), "incidents_open"):
            open_on_models.setdefault(iid, []).append(name)
    dqis = dqi_files()
    for iid, p in dqis.items():
        text = p.read_text()
        status = get_fields(text).get("status", "").split()[0].lower().strip(".") if get_fields(text).get("status") else ""
        if status not in DQI_STATUSES:
            errs.append(f"{rel(p)}: status '{status}' is not one of {', '.join(DQI_STATUSES)}")
        if status in DQI_DONE:
            if iid in open_on_models:
                errs.append(f"{iid} is {status} but still in incidents_open on {', '.join(open_on_models[iid])}")
            if get_fields(text).get("fixed by") in reverted:
                errs.append(f"{iid} is fixed by {get_fields(text)['fixed by']}, which was reverted")
    for iid, where in open_on_models.items():
        if iid not in dqis:
            errs.append(f"{iid} is in incidents_open on {', '.join(where)} but has no incident file")

    adrs = adr_files()
    for aid, p in adrs.items():
        text = p.read_text()
        st = adr_status(text)
        if st not in ADR_STATUSES:
            errs.append(f"{rel(p)}: status '{get_fields(text).get('status', '')}' does not start with one of {', '.join(ADR_STATUSES)}")
        if st == "superseded":
            by = re.search(r"ADR-\d{3}", get_fields(text).get("status", ""))
            if not by or by.group(0) not in adrs:
                errs.append(f"{rel(p)}: superseded, but the replacing ADR is missing or unknown")
    for name, p in models.items():
        for a in get_meta_list(p.read_text(), "adr"):
            if a not in adrs:
                errs.append(f"{rel(p)}: meta adr {a} has no ADR file")
    if errs:
        die("\n  ".join(["check failed:"] + errs))
    print(f"ok: {len(seen)} change file(s), {len(dqis)} incident(s), {len(adrs)} ADR(s) consistent")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    n = sub.add_parser("new")
    n.add_argument("--kind", choices=sorted(KINDS))
    n.add_argument("--summary")
    n.add_argument("--why")
    for f in LIST_FIELDS:
        n.add_argument(f"--{f}", nargs="+", default=[])
    n.set_defaults(fn=cmd_new)

    inc = sub.add_parser("incident").add_subparsers(dest="sub", required=True)
    o = inc.add_parser("open")
    o.add_argument("--title", required=True)
    o.add_argument("--summary", required=True)
    o.add_argument("--severity", choices=SEVERITIES, required=True)
    o.add_argument("--dimension", required=True)
    o.add_argument("--domain", required=True)
    o.add_argument("--owner", required=True)
    o.add_argument("--affected", nargs="+", required=True)
    o.add_argument("--detected")
    o.add_argument("--detection")
    o.add_argument("--impact")
    o.set_defaults(fn=cmd_incident_open)
    rc = inc.add_parser("root-cause")
    rc.add_argument("id")
    rc.add_argument("--text", required=True)
    rc.set_defaults(fn=cmd_incident_root_cause)
    nt = inc.add_parser("note")
    nt.add_argument("id")
    nt.add_argument("--text", required=True)
    nt.add_argument("--status", choices=["open", "triaged", "investigating"])
    nt.set_defaults(fn=cmd_incident_note)

    adr = sub.add_parser("adr").add_subparsers(dest="sub", required=True)
    an = adr.add_parser("new")
    an.add_argument("--title", required=True)
    an.add_argument("--status", default="proposed")
    an.add_argument("--category")
    an.add_argument("--deciders", required=True)
    an.add_argument("--consulted")
    an.add_argument("--related", nargs="+", default=[])
    an.add_argument("--applies-to")
    an.add_argument("--supersedes")
    an.add_argument("--body", required=True, help="path, or - for stdin")
    an.set_defaults(fn=cmd_adr_new)
    ast = adr.add_parser("status")
    ast.add_argument("id")
    ast.add_argument("status")
    ast.set_defaults(fn=cmd_adr_status)
    adr.add_parser("index").set_defaults(fn=cmd_adr_index)

    r = sub.add_parser("release")
    r.add_argument("version")
    r.add_argument("--title", help="one line for the changelog, like 'Earned Income Variance Report'")
    r.add_argument("--dry-run", action="store_true")
    r.set_defaults(fn=cmd_release)

    sub.add_parser("check").set_defaults(fn=cmd_check)
    args = p.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
