-- DPR_NARRATIVE table and daily task for AI-generated analyst notes
-- ---------------------------------------------------------------------------
-- Run this once to create the target table and the scheduled task.
-- The task fires after the DPR load completes (chain it to your refresh task)
-- or on a CRON schedule before the Power BI subscription fires.
--
-- Prerequisites:
--   - rpt_dpr_narrative_brief view must exist (dbt build)
--   - CORTEX_USER database role or equivalent for SNOWFLAKE.CORTEX.COMPLETE
--   - Warehouse must be specified (task uses caller's warehouse)
-- ---------------------------------------------------------------------------

-- Resolve against the session database: run USE DATABASE <target> first
-- (dev: NS11MM_DW_DEV, prod: NS11MM_DW_PROD). ADR-019 / 7.5.3 portability pattern.
USE SCHEMA MARTS;

-- 1. Target table: one row per day, append-only
CREATE TABLE IF NOT EXISTS MARTS.DPR_NARRATIVE (
    report_date       DATE          NOT NULL,
    headline          VARCHAR(500),
    narrative         VARCHAR(4000) NOT NULL,
    watch_items       VARIANT,                   -- array of strings, nullable
    brief_json        VARIANT       NOT NULL,    -- exact input the model saw (audit)
    tokens_used       INT,
    model             VARCHAR(100)  NOT NULL,
    generated_at      TIMESTAMP_NTZ NOT NULL,

    CONSTRAINT pk_dpr_narrative PRIMARY KEY (report_date)
);

COMMENT ON TABLE MARTS.DPR_NARRATIVE IS
    'AI-generated daily analyst notes for the DPR. One row per report_date. '
    'brief_json stores the exact deterministic facts the model received — full audit trail. '
    'Generated by task T_DPR_NARRATIVE via SNOWFLAKE.CORTEX.COMPLETE.';


-- 2. Wrapper view for Power BI (thin projection, matches PBI naming convention)
CREATE OR REPLACE VIEW MARTS.DPR_PBI_NARRATIVE AS
SELECT
    report_date,
    headline,
    narrative,
    watch_items
FROM MARTS.DPR_NARRATIVE;

COMMENT ON VIEW MARTS.DPR_PBI_NARRATIVE IS
    'Power BI consumption view over DPR_NARRATIVE. Import into the DPR model and relate on report_date.';

GRANT SELECT ON VIEW MARTS.DPR_PBI_NARRATIVE TO ROLE POWERBI_ROLE;


-- 3. Daily task: generate narrative from brief
-- Option A: chain after your DPR refresh task (recommended)
--   AFTER MARTS.T_DPR_DAILY_LOAD
-- Option B: fixed CRON (adjust timezone/time to fire before PBI subscription)
--   SCHEDULE = 'USING CRON 30 5 * * * America/New_York'

CREATE OR REPLACE TASK MARTS.T_DPR_NARRATIVE
    WAREHOUSE = MONITORING_WH   -- tasks run on MONITORING_WH per SNOWFLAKE_SETTINGS.md
    SCHEDULE  = 'USING CRON 30 5 * * * America/New_York'
    COMMENT   = 'Generates AI analyst note for the DPR from the narrative brief. Runs daily before PBI subscription.'
AS
INSERT INTO MARTS.DPR_NARRATIVE (report_date, headline, narrative, watch_items, brief_json, tokens_used, model, generated_at)
WITH brief AS (
    SELECT report_date, brief_json
    FROM MARTS.RPT_DPR_NARRATIVE_BRIEF
    WHERE report_date = (SELECT MAX(report_date) FROM MARTS.RPT_DPR_NARRATIVE_BRIEF)
      -- Skip if already generated today
      AND report_date NOT IN (SELECT report_date FROM MARTS.DPR_NARRATIVE)
),
generated AS (
    SELECT
        b.report_date,
        b.brief_json,
        SNOWFLAKE.CORTEX.COMPLETE(
            'claude-sonnet-4-6',
            [
                {'role': 'system', 'content': $$You are the analyst writing the "Analyst Notes" section of the National September 11 Memorial & Museum Daily Performance Report, read each morning by museum leadership.

Write 3 to 5 sentences summarizing the day's performance.

Rules:
- Use ONLY the figures in the JSON below. Do not invent, estimate, or compute any number that is not present. If something is not in the data, do not mention it.
- Lead with Total Estimated Revenue vs budget, then name the 1-2 biggest drivers from top_budget_movers / top_dod_movers.
- Prefer same-day-prior-week (wow_pct) over day-over-day when describing attendance and retail, since weekdays differ structurally.
- If is_commemoration_day or in_commemoration_window is true, explicitly note that elevated figures reflect the commemoration period, not underlying trend.
- When a line item has no budget (budget is null), describe it in absolute terms or vs prior period only.
- Neutral, factual, executive tone. No speculation about causes beyond what the movers show. No emojis, no bullet points, no headers.
- Format currency as $X,XXX. Format percentages as X.X%. Use "ahead of budget" / "behind budget" rather than positive/negative variance.
- Keep watch_items to genuinely notable signals (7-day direction changes, large WoW swings); omit if nothing warrants attention.$$},
                {'role': 'user', 'content': b.brief_json::STRING}
            ],
            {
                'response_format': {
                    'type': 'json',
                    'schema': {
                        'type': 'object',
                        'properties': {
                            'headline': {
                                'type': 'string',
                                'description': 'One-line summary suitable for a card title, max 12 words'
                            },
                            'narrative': {
                                'type': 'string',
                                'description': 'The 3-5 sentence analyst note'
                            },
                            'watch_items': {
                                'type': 'array',
                                'items': {'type': 'string'},
                                'description': 'Optional: 0-3 short items worth monitoring'
                            }
                        },
                        'required': ['headline', 'narrative']
                    }
                },
                'max_tokens': 600,
                'temperature': 0.1
            }
        ) AS raw_response
    FROM brief b
)
SELECT
    report_date,
    raw_response:structured_output[0]:raw_message:headline::STRING,
    raw_response:structured_output[0]:raw_message:narrative::STRING,
    raw_response:structured_output[0]:raw_message:watch_items,
    brief_json,
    raw_response:usage:total_tokens::INT,
    'claude-sonnet-4-6',
    CURRENT_TIMESTAMP()
FROM generated
WHERE report_date IS NOT NULL;

-- Task is created SUSPENDED by default. Resume when ready:
-- ALTER TASK MARTS.T_DPR_NARRATIVE RESUME;
