-- NS11MM Data Platform — Developer Workspace Setup
-- Run once per new developer to provision their personal dev environment.
-- Replace <USERNAME> with the developer's Snowflake username (e.g. DIANA, PHINN).

-- 1. Create personal dev database
CREATE DATABASE IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>
    COMMENT = 'Personal dev database for <USERNAME>';

-- 2. Create schemas mirroring production
CREATE SCHEMA IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>.RAW;
CREATE SCHEMA IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>.SILVER;
CREATE SCHEMA IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>.GOLD;
CREATE SCHEMA IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>.ML_FEATURES;

-- 3. Grant permissions
GRANT USAGE ON DATABASE NS11MM_DW_DEV_<USERNAME> TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE NS11MM_DW_DEV_<USERNAME> TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NS11MM_DW_DEV_<USERNAME> TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE NS11MM_DW_DEV_<USERNAME> TO ROLE TRANSFORMER_ROLE;

-- 4. Create audit log table
CREATE TABLE IF NOT EXISTS NS11MM_DW_DEV_<USERNAME>.SILVER.DBT_RUN_AUDIT_LOG (
    model_name          VARCHAR,
    run_timestamp       TIMESTAMP_TZ,
    status              VARCHAR,
    rows_affected       INTEGER,
    error_message       VARCHAR
);

-- 5. Grant LOADER_ROLE access to RAW schema for pipeline testing
GRANT USAGE ON DATABASE NS11MM_DW_DEV_<USERNAME> TO ROLE LOADER_ROLE;
GRANT USAGE ON SCHEMA NS11MM_DW_DEV_<USERNAME>.RAW TO ROLE LOADER_ROLE;
GRANT INSERT, CREATE TABLE ON SCHEMA NS11MM_DW_DEV_<USERNAME>.RAW TO ROLE LOADER_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA NS11MM_DW_DEV_<USERNAME>.RAW TO ROLE LOADER_ROLE;

-- Existing team members (run-once, already provisioned or provision now):
-- CREATE DATABASE IF NOT EXISTS NS11MM_DW_DEV_JMYERS;
-- CREATE DATABASE IF NOT EXISTS NS11MM_DW_DEV_KRAMSEY;
-- CREATE DATABASE IF NOT EXISTS NS11MM_DW_DEV_DIANA;
