-- CARTS_NARRATIVE table and daily task for AI-generated Carts Analysis analyst notes
-- ---------------------------------------------------------------------------
-- Twin of scripts/setup_retail_narrative.sql. Run once to create the target
-- table, the Power BI wrapper view, and the scheduled task. Chain the task
-- after the nightly CounterPoint retail load (or CRON before the Power BI
-- subscription).
--
-- Prerequisites:
--   - rpt_carts_narrative_brief view must exist (dbt build)
--   - CORTEX_USER database role or equivalent for SNOWFLAKE.CORTEX.COMPLETE
--   - Warehouse specified (task uses caller's warehouse)
--
-- SYNC GUARD: the system prompt below must stay verbatim-identical to the
-- prompt in models/marts/reports/rpt_carts_narrative.sql. Edit both or
-- neither.
-- ---------------------------------------------------------------------------

-- Resolve against the session database: run USE DATABASE <target> first
-- (dev: NS11MM_DW_DEV, prod: NS11MM_DW_PROD). ADR-019 / 7.5.3 portability pattern.
USE SCHEMA MARTS;

-- 1. Target table: one row per day, append-only
CREATE TABLE IF NOT EXISTS MARTS.CARTS_NARRATIVE (
    report_date       DATE          NOT NULL,
    headline          VARCHAR(500),
    narrative         VARCHAR(4000) NOT NULL,
    watch_items       VARIANT,                   -- array of strings, nullable
    brief_json        VARIANT       NOT NULL,    -- exact input the model saw (audit)
    tokens_used       INT,
    model             VARCHAR(100)  NOT NULL,
    generated_at      TIMESTAMP_NTZ NOT NULL,

    CONSTRAINT pk_carts_narrative PRIMARY KEY (report_date)
);

COMMENT ON TABLE MARTS.CARTS_NARRATIVE IS
    'AI-generated daily analyst notes for the Retail Carts Analysis report. One row per report_date. '
    'brief_json stores the exact deterministic facts the model received - full audit trail. '
    'Generated by task T_CARTS_NARRATIVE via SNOWFLAKE.CORTEX.COMPLETE.';


-- 2. Wrapper view for Power BI (thin projection, matches PBI naming convention)
CREATE OR REPLACE VIEW MARTS.CARTS_PBI_NARRATIVE AS
SELECT
    report_date,
    headline,
    narrative,
    watch_items
FROM MARTS.CARTS_NARRATIVE;

COMMENT ON VIEW MARTS.CARTS_PBI_NARRATIVE IS
    'Power BI consumption view over CARTS_NARRATIVE. Import into the Carts Analysis model and relate on report_date.';

GRANT SELECT ON VIEW MARTS.CARTS_PBI_NARRATIVE TO ROLE POWERBI_ROLE;


-- 3. Daily task: generate narrative from brief
-- Option A: chain after the nightly CounterPoint retail load task (recommended)
-- Option B: fixed CRON (adjust to fire before the PBI subscription)
CREATE OR REPLACE TASK MARTS.T_CARTS_NARRATIVE
    WAREHOUSE = MONITORING_WH   -- tasks run on MONITORING_WH per SNOWFLAKE_SETTINGS.md
    SCHEDULE  = 'USING CRON 30 5 * * * America/New_York'
    COMMENT   = 'Generates AI analyst note for the Retail Carts Analysis report from the narrative brief. Runs daily before PBI subscription.'
AS
INSERT INTO MARTS.CARTS_NARRATIVE (report_date, headline, narrative, watch_items, brief_json, tokens_used, model, generated_at)
WITH brief AS (
    SELECT report_date, brief_json
    FROM MARTS.RPT_CARTS_NARRATIVE_BRIEF
    WHERE report_date = (SELECT MAX(report_date) FROM MARTS.RPT_CARTS_NARRATIVE_BRIEF)
      AND report_date NOT IN (SELECT report_date FROM MARTS.CARTS_NARRATIVE)
),
generated AS (
    SELECT
        b.report_date,
        b.brief_json,
        SNOWFLAKE.CORTEX.COMPLETE(
            'claude-sonnet-4-6',
            [
                {'role': 'system', 'content': $$You are the analyst writing the "Analyst Notes" section of the National September 11 Memorial & Museum Retail Carts Analysis report, read by retail leadership.

Write 2 to 4 sentences summarizing the day's memorial carts performance.

Rules:
- Use ONLY the figures in the JSON below. Do not invent, estimate, or compute any number that is not present. If something is not in the data, do not mention it. Capture rate and per-cap measures are not in the data — never mention them.
- Lead with carts sales and customers, then average sale or gross profit if notable.
- Prefer same-weekday-last-week (vs_same_weekday_last_week) over day-over-day when describing movement, since weekdays differ. Mention the year-over-year comparison only when the swing is large.
- If is_commemoration_day or in_commemoration_window is true, explicitly note that elevated figures reflect the commemoration period, not underlying trend.
- Neutral, factual, executive tone. No speculation about causes (weather, events) beyond what the data shows. No emojis, no bullet points, no headers.
- Format currency as $X,XXX. Format percentages as X.X%.
- Keep watch_items to genuinely notable signals (a sustained 7-day decline, a large vs-last-week swing); omit if nothing warrants attention.$$},
                {'role': 'user', 'content': b.brief_json::STRING}
            ],
            {
                'response_format': {
                    'type': 'json',
                    'schema': {
                        'type': 'object',
                        'properties': {
                            'headline':    {'type': 'string', 'description': 'One-line summary suitable for a card title, max 12 words'},
                            'narrative':   {'type': 'string', 'description': 'The 2-4 sentence analyst note'},
                            'watch_items': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Optional: 0-3 short items worth monitoring'}
                        },
                        'required': ['headline', 'narrative']
                    }
                },
                'max_tokens': 600,
                'temperature': 0.1
            }
        ) AS raw_response
    FROM brief b
)
SELECT
    report_date,
    raw_response:structured_output[0]:raw_message:headline::STRING,
    raw_response:structured_output[0]:raw_message:narrative::STRING,
    raw_response:structured_output[0]:raw_message:watch_items,
    brief_json,
    raw_response:usage:total_tokens::INT,
    'claude-sonnet-4-6',
    CURRENT_TIMESTAMP()
FROM generated
WHERE report_date IS NOT NULL;

-- Task is created SUSPENDED by default. Resume when ready:
-- ALTER TASK MARTS.T_CARTS_NARRATIVE RESUME;
